<% adapter = ENV.fetch("SIGNONOTRON2_DB_ADAPTER", "mysql") %>
mysql_default: &mysql_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: signonotron2
  password: signonotron2
  pool: 5

postgresql_default: &postgresql_default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *<%= adapter %>_default
  database: signonotron2_development

test: &test
  <<: *<%= adapter %>_default
  database: signonotron2_test

production:
  <<: *<%= adapter %>_default
  database: halberd_production
  username: halberd
  password:
